CREATE USER 'repl_user'@'%' IDENTIFIED BY 'repl_password';

GRANT REPLICATION SLAVE ON *.* TO 'repl_user'@'%' IDENTIFIED BY 'repl_password';

#SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = WARN;
#SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;
#SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;
#SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;
#SET @@GLOBAL.GTID_MODE = ON;

CHANGE MASTER TO MASTER_HOST='db1', MASTER_USER='repl_user', MASTER_PASSWORD='repl_password', MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=154;
#CHANGE MASTER TO MASTER_HOST='db1', MASTER_USER='repl_user', MASTER_PASSWORD='repl_password', MASTER_AUTO_POSITION=1;

START SLAVE;
